import { Amplify } from "aws-amplify";

/**
 * `amplify_outputs.json` is generated by `npx ampx sandbox` / the Amplify build
 * and is not committed. Globbing it keeps the app building before the backend
 * has ever been deployed — a plain import would fail to resolve.
 */
const outputModules = import.meta.glob("/amplify_outputs.json", { eager: true }) as Record<
  string,
  { default: Record<string, unknown> }
>;

const outputs = Object.values(outputModules)[0]?.default;

/** True once a backend has been deployed and its outputs are present. */
export const isBackendConfigured = Boolean(outputs);

/** Base URL of the REST API, e.g. https://abc123.execute-api.us-east-2.amazonaws.com/api */
export const apiBaseUrl = String(
  (outputs?.custom as { apiUrl?: string } | undefined)?.apiUrl ?? "",
).replace(/\/$/, "");

if (outputs) {
  Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);
}
